FROM rocker/r-ver:latest

LABEL org.opencontainers.image.authors="us@couchbits.com"
LABEL org.opencontainers.image.vendor="couchbits GmbH"

ENV PROJECT_DIR /moveapps-r-sdk
ENV RENV_PATHS_CACHE=/renv/cache

# the app
WORKDIR $PROJECT_DIR
COPY renv.lock ./
COPY sdk.R ./
COPY src/ ./src/
COPY data/ ./data/
COPY tests/ ./tests/
COPY RFunction.R/ ./

RUN R -e "install.packages('renv', repos = 'https://ftp.gwdg.de/pub/misc/cran')"

RUN R -e 'testthat::test_dir("tests")'
